config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  resources :attendances, only: :create
  resources :events do
    resources :invites, only: [:new, :create]
  end
  resources :users, only: [:show, :index]
  get "/signup" => "users#new"
  post "/signup" => "users#create"
  get "/signin" => "sessions#new"
  post "/signin" => "sessions#create"
  delete "/signout" => "sessions#destroy"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events_hosted, class_name: "Event", foreign_key: :host_id, dependent: :destroy
  has_many :attendances, foreign_key: :attendee_id, dependent: :destroy
  has_many :events_attended, through: :attendances, source: :event_attended
  has_many :invites_sent, class_name: "Invite", foreign_key: :inviter_id, dependent: :destroy
  has_many :invites_received, class_name: "Invite", foreign_key: :invitee_id, dependent: :destroy
  has_many :events_invited_to, class_name: "Event", through: :invites_received, source: :event
  before_save { email.downcase! }
  has_secure_password
  validates :name, presence: true,
                   length: { maximum: 50 }
  validates :email, presence: true,
                    length: { maximum: 250 },
                    format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true,
                       length: { minimum: 6 }
                       
  def self.digest(password)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST
                                                : BCrypt::Engine.cost
    BCrypt::Password.create(password, cost: cost)
  end
  
  def attending?(event)
    self.events_attended.exists? event
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to @user
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @events_hosted = @user.events_hosted
    @events_attended = @user.events_attended
    @invites_received = @user.invites_received.group_by(&:event)
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="row">
	<ul class="users-container col-md-6 col-md-offset-3">
	  <h1>Users</h1>
	  <% @users.each do |user| %>
	    <li class="user-block">
	      <%= link_to user.name, user_path(user) %>
	    </li>
	  <% end %>
	</ul>
</div>

app/views/users/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Signup</h1>
  <%= form_for @user, url: signup_path, class: "form-horizontal" do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group">  
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">  
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="form-group">  
      <%= f.submit "Sign up", class: ["btn", "btn-primary"] %>
    </div
  <% end %>
</div>

app/views/users/show.html.erb
<h1><u><%= @user.name %>'s Profile</u></h1>

<% if @events_hosted.any? %>
  <h3>Events hosted</h3>
  <ul>
    <% @events_hosted.each do |event| %>
      <li>
        <%= link_to event.title, event_path(event) %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if @events_attended.any? %>
  <h3>Events attended</h3>
  <ul>
    <% @events_attended.each do |event| %>
      <li>
        <%= link_to event.title, event_path(event) %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if current_user?(@user.id) && @invites_received.any? %>
  <h3>Pending invites</h3>
  <div class="container-fluid">
    <% @invites_received.each do |event, invite| %>
      <div class="row">
        <div class="col-md-4"><%= invite.map{ |i| i.inviter.name }.join(",") %> <%= invite.many? ? "invite" : "invites" %> you to <%= link_to event.title, event_path(event) %></div>
        <div class="col-md-2"><%= button_to "Accept", attendances_path(attendance: {event_attended_id: event.id} ), method: :post, class: ["btn", "btn-default"] %></div>
      </div>
    <% end %>
  </div>
<% end %>