config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  resources :attendances, only: :create
  resources :events do
    resources :invites, only: [:new, :create]
  end
  resources :users, only: [:show, :index]
  get "/signup" => "users#new"
  post "/signup" => "users#create"
  get "/signin" => "sessions#new"
  post "/signin" => "sessions#create"
  delete "/signout" => "sessions#destroy"
end

app/views/sections/_header.html.erb
<header class="navbar navbar-static-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <%= link_to "Events", root_path, class: "navbar-brand" %>
    </div>
    
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Users", users_path %></li>
        <% if signed_in? %>
        <li><%= link_to "+Event", new_event_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to(content_tag(:span, "", class: "glyphicon glyphicon-user") + " Profile", current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to(content_tag(:span, "", class: "glyphicon glyphicon-log-out") + " Sign Out", signout_path, method: :delete) %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to(content_tag(:span, "", class: "glyphicon glyphicon-user") + " Sign Up", signup_path) %></li>
        <li><%= link_to(content_tag(:span, "", class: "glyphicon glyphicon-log-in") + " Sign In", signin_path) %></li>
        <% end %>
      </ul>
    </div>
    
  </div>
</header>