config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  resources :attendances, only: :create
  resources :events do
    resources :invites, only: [:new, :create]
  end
  resources :users, only: [:show, :index]
  get "/signup" => "users#new"
  post "/signup" => "users#create"
  get "/signin" => "sessions#new"
  post "/signin" => "sessions#create"
  delete "/signout" => "sessions#destroy"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :host, class_name: "User"
  has_many :attendances, foreign_key: :event_attended_id, dependent: :destroy
  has_many :attendees, through: :attendances
  has_many :invites, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  scope :unfinished, -> { where("time_end > ?", Time.now ) }
  scope :finished, -> { where("time_end <= ?", Time.now ) }
  validates :title, presence: true,
                    length: { maximum: 50 }
  validates :description, length: { maximum: 1000 }
  validates :venue, presence: true, 
                    length: { maximum: 50 }
  validates :time_start, presence: true
  validates :time_end, presence: true
  
  validate :time_end_cannot_be_in_the_past,
           :time_end_must_be_after_time_start
           
  private
  
    def time_end_cannot_be_in_the_past
      if time_end.present? && time_end < DateTime.now
        errors.add(:time_end, "can't be in the past.")
      end
    end
  
    def time_end_must_be_after_time_start
      if time_end.present? && time_start.present? && time_end < time_start
        errors.add(:time_end, "is invalid.")
      end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create, :destroy]
  
  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
    @invites = @event.invites.group_by(&:invitee)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.host = current_user
    if @event.save
      Attendance.create(attendee: current_user, event_attended: @event)
      redirect_to event_path(@event)
    else
      render "new"
    end
  end

  def index
    @unfinished = Event.unfinished
    @finished = Event.finished
  end
  
  private
  
    def event_params
      params.require(:event).permit(:title, :description, :time_start, :time_end, :venue)
    end
    
    def signed_in_user
      redirect_to signin_path unless signed_in?
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="row">
  <ul class="events-container">
    <h1>Events</h1>
    <% @unfinished.each do |event| %>
      <li class="event-block col-sm-6 col-md-6 col-lg-4">
        <div class="event-box">
          <span class="event-title"><%= link_to event.title, event_path(event) %></span>
          <span class="event-host">Host: <%= link_to event.host.name, event.host %></span>
          <span class="event-sched">Time: <%= event.time_start.strftime("%a %d %b %Y, %I:%M %p").upcase %></span>
          <span class="event-venue">Venue: <%= event.venue %></span>
          <span class="event-desc"><%= simple_format event.description %></span>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<div class="row">
  <ul>
    <h1>Past Events</h1>
    <% @finished.each do |event| %>
      <li class="event-block col-sm-6 col-md-6 col-lg-4">
        <div class="event-box">
          <span class="event-title"><%= link_to event.title, event_path(event) %></span>
          <span class="event-host">Host: <%= link_to event.host.name, event.host %></span>
          <span class="event-sched">Time: <%= event.time_start.strftime("%a %d %b %Y, %I:%M %p").upcase %></span>
          <span class="event-venue">Venue: <%= event.venue %></span>
          <span class="event-desc"><%= simple_format event.description %></span>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/events/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Create Event</h1>
  <%= form_for @event, class: "form-horizontal" do |f| %>
    <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
    <%= f.label :venue %>
    <%= f.text_field :venue, class: "form-control" %>
    </div>
    <div class="form-group">
    <%= f.label :time_start %>
    <%= f.datetime_field :time_start, class: "form-control" %>
    </div>
    <div class="form-group">
    <%= f.label :time_end %>
    <%= f.datetime_field :time_end, class: "form-control" %>
    </div>
    <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
    <%= f.submit "Create", class: ["btn", "btn-primary"] %>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<h1><u><%= @event.title %></u></h1>
<table class="event-info">
  <tr>
    <td>Hosted by:</td><td><%= link_to @event.host.name, user_path(@event.host) %></td>
  </tr>
  <tr>
    <td>Venue:</td><td><%= @event.venue %></td>
  </tr>
  <tr>
    <td>Start:</td><td><%= @event.time_start.strftime("%a %d %b %Y, %I:%M %p") %></td>
  </tr>
  <tr>
    <td>End:</td><td><%= @event.time_end.strftime("%a %d %b %Y, %I:%M %p") %></td>
  </tr>
</table>

<blockquote>
  <%= simple_format @event.description %>
</blockquote>

<div class="row">
  <div class="col-md-3">
    <h3>Attendees:</h3>
    <ol>
      <% @attendees.each do |attendee| %>    
        <li><%= link_to attendee.name, attendee %></li>
      <% end %>
    </ol>
  </div>
  <div class="col-md-3">
    <h3>Pending Invites:</h3>
    <ol>
      <% @invites.each do |invitee, invites| %>    
        <li>
          <%= invites.map { |invite| invite.inviter.name }.join(", ") %>
          <%= invites.many? ? "invite" : "invites" %> <%= link_to invitee.name, invitee %>
        </li>
      <% end %>
    </ol>
  </div>
</div>

<% if signed_in? && already_attending?(@event.id) %>
  <%= button_to "Send Invites", new_event_invite_path(@event.id), class: ["btn", "btn-default"], method: :get %>
<% end %>